site_name: 深圳大学飞跃手册
repo_url: https://github.com/szu-feiyue/docs
edit_uri: edit/main/docs/
site_url: https://szu-feiyue.github.io
site_author: SZU Feiyue Team
copyright: 'Copyright &copy; 2024–2026 SZU Feiyue Team'

nav:
  - 首页:
    - index.md
    - 贡献: contribute.md
  - 留学:
    - overseas/index.md
    - 2026届:
      - Don · CUHK MiM: overseas/FinTech/2026/cases/Don.md
    - 2025届:
      - 陈天行 · HKU PhD@CS: overseas/CompSci/2025/cases/tianxingchen.md
      - 陈铭康 · HKU MSc@CS: overseas/CompSci/2025/cases/mingkangchen.md
      - 张硕 · NUS MSc@ECE: overseas/CompSci/2025/cases/shuozhang.md
    - 2024届:
      - 李晓璐 · Maryland PhD@Stat: overseas/CompSci/2024/cases/xiaoluli.md
      - 忆如 · Edinburgh MS@CS: overseas/CompSci/2024/cases/wenli.md
      - 苏嘉淇 · HKU MSc@CS: overseas/CompSci/2024/cases/jiaqisu.md
      - Anthony · HKUSTgz MSc@CS: overseas/CompSci/2024/cases/zihaotang.md
      - 快乐摸鱼生活 · HKUST MSc@TLE: overseas/CompSci/2024/cases/yuanlan.md
      - 苏政欣 · Duke MEM: overseas/CompSci/2024/cases/zhengxinsu.md
      - 陈同学 · UMacau DS: overseas/CompSci/2024/cases/nuochen.md
      - 赵子睿 · Rice MCS: overseas/CompSci/2024/cases/ziruizhao.md
    - 2023届:
      - 王楷盛 · NTU C&A: overseas/CompSci/2023/cases/kaishengwang.md
      - 徐子晴 · NUS MSc@VC: overseas/Economics/2023/cases/ziqingxu.md
    - 2022届:
      - 彭镇灿 · Rutgers PhD@CS: overseas/CompSci/2022/cases/zhencanpeng.md
      - 詹卓欣 · SFU PhD@CS: overseas/CompSci/2022/cases/zhuoxinzhan.md
  - 保研:
    - baoyan/index.md
    - 2026届:
      - 许若伦 · 北理 PhD@ICE: baoyan/Physics/2026/cases/ruolunxu.md
    - 2025届:
      - 朱宇飞 · 上科大@CS: baoyan/CompSci/2025/cases/yufeizhu.md
      - 钟昊天 · 浙大 PhD@CS: baoyan/CompSci/2025/cases/haotianzhong.md
      - 陈潇泳 · 北理工@CS: baoyan/CompSci/2025/cases/xiaoyongchen.md
      - 李深艺 · 北大 PhD@Matl: baoyan/CompSci/2025/cases/shenyili.md
      - Mia · 东南@CS: baoyan/CompSci/2025/cases/zhentingliao.md
      - 李林一 · 南开 PhD@CS: baoyan/CompSci/2025/cases/linyili.md
      - 宋宗硕 · 成电@CS: baoyan/CompSci/2025/cases/zhongshuosong.md
      - 张豪杰 · 深大 PhD@CS: baoyan/CompSci/2025/cases/haojiezhang.md
      - 陈镇熙 · 中大@CS: baoyan/CompSci/2025/cases/zhenxichen.md
      - 陈家豪 · 北大深圳@IC: baoyan/CompSci/2025/cases/jiahaochen.md
      - 陈婉纯 · 华南理工 PhD@CS: baoyan/CompSci/2025/cases/wanchunchen.md
      - 王淇 · 南科大@Math: baoyan/CompSci/2025/cases/qiwang.md
      - 吴骏 · 中科院: baoyan/GradStudies/2025/cases/junwu.md
      - 蒋畅之 · 中科院 PhD@Astro: baoyan/CompSci/2025/cases/changzhijiang.md
    - 2024届:
      - 苏梓瀚 · 清华深圳@CS: baoyan/CompSci/2024/cases/zihansu.md
      - 梁霈柔 · 中科大@CS: baoyan/CompSci/2024/cases/peirouliang.md
      - 汪贝琪 · 华科@CS: baoyan/CompSci/2024/cases/beiqiwang.md
      - 陈耿 · 北邮@CS: baoyan/CompSci/2024/cases/gengchen.md
      - 洪钊彦 · 人大 PhD@CS: baoyan/CompSci/2024/cases/zhaoyanhong.md
      - 刘涛 · 南开@CS: baoyan/CompSci/2024/cases/taoliu.md
      - 郭奕彤 · 清华深圳@药学: baoyan/CompSci/2024/cases/yitongguo.md
    - 2023届:
      - 许宏浩 · 深大 VCC@CS: baoyan/CompSci/2023/cases/honghaoxu.md
      - 曹弈轩 · 深大@CS: baoyan/CompSci/2023/cases/yixuancao.md
      - ywh · 厦大 MAC@CS: baoyan/CompSci/2023/cases/weihaoye.md
  - 考研:
    - kaoyan/index.md
    - 2026届:
      - 李尚憬 · 北理@计算机: kaoyan/CompSci/2026/cases/shangjingli.md
    - 2024届:
      - 颜治强 · 哈工深@CS: kaoyan/CompSci/2024/cases/zhiqiangyan.md
    - 2023届:
      - 许厚德 · 中音@作曲: kaoyan/Arts/2023/cases/houdexu.md
      - 梁洁瑜 · 复旦@心理学: kaoyan/Psychology/2023/cases/jieyuliang.md
      - 朱芮瑾 · 复旦@心理学: kaoyan/Psychology/2023/cases/ruijinzhu.md
      - 罗碧璇 · 上交@新传: kaoyan/Media/2023/cases/bixuanluo.md
      - 曾扬阳 · 中大@哲学: kaoyan/Philosophy/2023/cases/yangyangzeng.md
      - 王知超 · 上交@电信: kaoyan/InfoTech/2023/cases/zhichaowang.md
      - 蔡依晴 · 武大@民商法: kaoyan/Law/2023/cases/yiqingcai.md
      - 陈宇珺 · 法大@法学: kaoyan/Law/2023/cases/yujunchen.md
      - 谭琬潼 · 浙大@社会学: kaoyan/Sociology/2023/cases/wantongtan.md
      - 陈雨荷 · 清华@环境: kaoyan/ChemEnv/2023/cases/yuhechen.md
  - 就业:
    - jiuye/index.md
    - 2026届:
      - 关浩林 · Kasma 实习: jiuye/CompSci/2026/cases/haolinguan.md
      - 吴嘉楷 · 字节前端: jiuye/CompSci/2026/cases/jiakaiwu.md
    - 2025届:
      - 李伟力 · 量化交易: jiuye/CompSci/2025/cases/weilili.md
      - 陈梓淳 · 腾讯转正: jiuye/CompSci/2025/cases/zichunchen.md
      - 李佳乐 · 腾讯转正: jiuye/CompSci/2025/cases/jialeli.md
      - 闪闪 · 腾讯实习: jiuye/CompSci/2025/cases/yaqinshan.md
      - 叶可禾 · 腾讯实习: jiuye/CompSci/2025/cases/keheye.md
      - 正汰 · 字节: jiuye/InfoTech/2025/cases/taizheng.md
    - 2021届:
      - debug君 · 深信服 / 美团: jiuye/CompSci/2021/cases/zehongluo.md
theme:
  name: material
  language: zh
  logo: assets/szu.png
  favicon: assets/logo.svg
  font: false
  palette:
    scheme: default
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - announce.dismiss

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/szu-feiyue/docs
      name: GitHub

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - redirects:
      redirect_maps:
        liuxue/index.md: overseas/index.md
        liuxue/template.md: overseas/template.md
        liuxue/FinTech/2026/cases/Don.md: overseas/FinTech/2026/cases/Don.md
        liuxue/CompSci/2025/cases/tianxingchen.md: overseas/CompSci/2025/cases/tianxingchen.md
        liuxue/CompSci/2025/cases/mingkangchen.md: overseas/CompSci/2025/cases/mingkangchen.md
        liuxue/CompSci/2025/cases/shuozhang.md: overseas/CompSci/2025/cases/shuozhang.md
        liuxue/CompSci/2024/cases/xiaoluli.md: overseas/CompSci/2024/cases/xiaoluli.md
        liuxue/CompSci/2024/cases/wenli.md: overseas/CompSci/2024/cases/wenli.md
        liuxue/CompSci/2024/cases/jiaqisu.md: overseas/CompSci/2024/cases/jiaqisu.md
        liuxue/CompSci/2024/cases/zihaotang.md: overseas/CompSci/2024/cases/zihaotang.md
        liuxue/CompSci/2024/cases/yuanlan.md: overseas/CompSci/2024/cases/yuanlan.md
        liuxue/CompSci/2024/cases/zhengxinsu.md: overseas/CompSci/2024/cases/zhengxinsu.md
        liuxue/CompSci/2024/cases/nuochen.md: overseas/CompSci/2024/cases/nuochen.md
        liuxue/CompSci/2024/cases/ziruizhao.md: overseas/CompSci/2024/cases/ziruizhao.md
        liuxue/CompSci/2023/cases/kaishengwang.md: overseas/CompSci/2023/cases/kaishengwang.md
        liuxue/Economics/2023/cases/ziqingxu.md: overseas/Economics/2023/cases/ziqingxu.md
        liuxue/CompSci/2022/cases/zhencanpeng.md: overseas/CompSci/2022/cases/zhencanpeng.md
        liuxue/CompSci/2022/cases/zhuoxinzhan.md: overseas/CompSci/2022/cases/zhuoxinzhan.md
        main/contribute.md: contribute.md
  - search:
      lang:
        - zh
        - en
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
  - git-authors:
      show_contribution: true
